site_name: FastAPI Enterprise Template
site_description: A robust, professional-grade FastAPI boilerplate for enterprise applications
site_author: Your Name
site_url: https://your-domain.com

repo_name: your-org/fastapi-enterprise-template
repo_url: https://github.com/your-org/fastapi-enterprise-template
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: "material.extensions.emoji.to_svg"
      emoji_index: "material.extensions.emoji.twemoji"

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - Development:
    - Project Structure: development/structure.md
    - API Documentation: development/api.md
    - Database: development/database.md
    - Testing: development/testing.md
  - Deployment:
    - Docker: deployment/docker.md
    - Production: deployment/production.md
    - CI/CD: deployment/ci-cd.md
  - API Reference:
    - Endpoints: api/endpoints.md
    - Models: api/models.md
    - Schemas: api/schemas.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/fastapi-enterprise-template
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-handle
