"""Add postal codes table and user fields

Revision ID: bb20d7236d61
Revises: 0001
Create Date: 2025-07-09 07:49:10.575018

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bb20d7236d61"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("address", sa.String(), nullable=True))
    op.add_column("users", sa.Column("age", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("postal_code_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_users_postal_code_id"), "users", ["postal_code_id"], unique=False
    )
    op.create_foreign_key(None, "users", "postal_codes", ["postal_code_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_postal_code_id"), table_name="users")
    op.drop_column("users", "postal_code_id")
    op.drop_column("users", "age")
    op.drop_column("users", "address")
    # ### end Alembic commands ###
